routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// Auth::routes();

Route::get('/&&anakita-login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('/&&anakita-login', 'Auth\LoginController@login');
Route::post('/&&anakita-logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
Route::get('/&&anakita-register', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('/&&anakita-register', 'Auth\RegisterController@register');

Route::get('/&&anakita-password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('/&&anakita-password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('/&&anakita-password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('/&&anakita-password/reset', 'Auth\ResetPasswordController@reset')->name('password.update');




Route::get('/home', 'HomeController@index')->name('home');
Route::resource('/data-anak', 'DataAnakController');
Route::resource('/data-visual', 'DataVisualController');
Route::resource('/riwayat-vaksinasi', 'VaksinasiController');
Route::resource('/riwayat-kesehatan', 'KesehatanController');
Route::resource('/yayasan', 'YayasanController');
Route::resource('/user', 'UsersController');
Route::resource('/daftar-penyakit', 'DaftarPenyakitController');
// Route::resource('/log', 'AuditController');
    
Route::get('/profile/{id}','YayasanController@profile')->name('profile');
Route::post('/profile/{id}','YayasanController@updateProfile')->name('updateProfile');
Route::post('/data-anak/cari','DataAnakController@cari')->name('cariAnak');
Route::get('/log','HomeController@getAudit');


// Route for Excel and PDF Report
Route::get('excel/vaksinasi/{id}','VaksinasiController@export')->name('export.vaksinasi');
Route::get('excel/kesehatan/{id}','KesehatanController@export')->name('export.kesehatan');
Route::get('excel/data-anak/{id}','DataAnakController@export')->name('export.data-anak');
Route::get('excel/yayasan/{id}','YayasanController@export')->name('export.data-yayasan');

Route::get('pdf/vaksinasi/{id}', 'VaksinasiController@pdf')->name('pdf.vaksinasi');
Route::get('pdf/kesehatan/{id}', 'KesehatanController@pdf')->name('pdf.kesehatan');

Route::get('pdf/data-anak/{id}', 'DataAnakController@pdfDataAnak')->name('pdf.data-anak');
Route::get('pdf/data-anak/vaksinasi/{id}', 'DataAnakController@pdfVaksinasi')->name('pdf.data-anak.vaksinasi');
Route::get('pdf/data-anak/kesehatan/{id}', 'DataAnakController@pdfKesehatan')->name('pdf.data-anak.kesehatan');

Route::get('pdf/yayasan/{id}', 'YayasanController@pdfDataYayasan')->name('pdf.data-yayasan');
Route::get('pdf/yayasan/data-anak/{id}', 'YayasanController@pdfDataAnak')->name('pdf.data-yayasan.data-anak');
Route::get('pdf/yayasan/vaksinasi/{id}', 'YayasanController@pdfVaksinasi')->name('pdf.data-yayasan.vaksinasi');
Route::get('pdf/yayasan/kesehatan/{id}', 'YayasanController@pdfKesehatan')->name('pdf.data-yayasan.kesehatan');

app/Models/Yayasan.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Yayasan extends Model 
{
    protected $fillable = [
        'nama_yayasan',
        'foto_yayasan',
        'alamat',
        'no_telp',
        'tgl_berdiri',
        'visi',
        'misi',
        'tentang_yayasan',
        'nama_pengurus',
        'no_telp_pengurus',
        'alamat_pengurus',
        'jenis_kelamin_pengurus',
        'foto_ktp_pengurus',
    ];

    public function vaksinasi()
    {
        return $this->hasMany('App\Models\Vaksinasi', 'id_yayasan', 'id');
    }

    public function kesehatan()
    {
        return $this->hasMany('App\Models\Kesehatan', 'id_yayasan', 'id');
    }
    public function users()
    {
        return $this->hasMany('App\User','id_yayasan','id');
    }
    public function dataAnak()
    {
        return $this->hasMany('App\Models\DataAnak','id_yayasan','id');
    }

    // function for onDelete Cascade
    public static function boot()
    {
        parent::boot();

        static::deleted(function($yayasan){
            $yayasan->vaksinasi()->delete();
            $yayasan->kesehatan()->delete();
            $yayasan->users()->delete();
            $yayasan->dataAnak()->delete();
        });
    }
}

app/Http/Controllers/YayasanController.php
<?php

namespace App\Http\Controllers;

use PDF;
use App\Exports\YayasanExport;
use App\Models\DataAnak;
use App\Models\Kesehatan;
use App\Models\Vaksinasi;
use Illuminate\Support\Facades\Auth;
use Illuminate\Http\Request;
use App\Models\Yayasan;
use Maatwebsite\Excel\Facades\Excel;

class YayasanController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['datas'] = Yayasan::all();
        return view('backend.yayasan.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.yayasan.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $foto_yayasan = "";
        $foto_ktp = "";
        if ($request->hasFile('foto_yayasan') && $request->hasFile('foto_ktp_pengurus')) {
            $path = 'images';
            $file1 = $request->foto_yayasan;
            $file2 = $request->foto_ktp_pengurus;
            $extension1 = $file1->getClientOriginalExtension();
            $extension2 = $file2->getClientOriginalExtension();
            $fileName1 = rand(1111, 9999) . "." . $extension1;
            $fileName2 = rand(1111, 9999) . "." . $extension2;
            $file1->move($path, $fileName1);
            $file2->move($path, $fileName2);

            $foto_yayasan = $fileName1;
            $foto_ktp = $fileName2;
        }

        $input['nama_yayasan'] = $request->nama_yayasan;
        $input['nama_pengurus'] = $request->nama_pengurus;
        $input['no_telp_pengurus'] = $request->no_telp_pengurus;
        $input['alamat_pengurus'] = $request->alamat_pengurus;
        $input['jenis_kelamin_pengurus'] = $request->jenis_kelamin_pengurus;
        $input['foto_ktp_pengurus'] = $foto_ktp;
        $input['foto_yayasan'] = $foto_yayasan;
        $input['alamat'] = $request->alamat;
        $input['no_telp'] = $request->no_telp;
        $input['tgl_berdiri'] = $request->tgl_berdiri;
        $input['visi'] = $request->visi;
        $input['misi'] = $request->misi;
        $input['tentang_yayasan'] = $request->tentang_yayasan;
        Yayasan::create($input);

        return redirect()->route('yayasan.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data['yayasan'] = Yayasan::findOrFail($id);
        return view('backend.yayasan.show', $data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['yayasan'] = Yayasan::find($id);
        return view('backend.yayasan.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = Yayasan::findOrFail($id);
        // dd($request);
        if ($request->file('foto_yayasan') == "") {
            $data->foto_yayasan = $data->foto_yayasan;
        } else {
            $path = 'images';
            $file = $request->foto_yayasan;
            $extension = $file->getClientOriginalExtension();
            $fileName = rand(1111, 9999) . "." . $extension;
            $file->move($path, $fileName);

            $data->foto_yayasan = $fileName;
        }

        if ($request->file('foto_ktp_pengurus') == "") {
            $data->foto_ktp_pengurus = $data->foto_ktp_pengurus;
        } else {
            $path = 'images';
            $file = $request->foto_ktp_pengurus;
            $extension = $file->getClientOriginalExtension();
            $fileName = rand(1111, 9999) . "." . $extension;
            $file->move($path, $fileName);
            $data->foto_ktp_pengurus = $fileName;
        }
        

        if ($request->jenis_kelamin_pengurus == "") {
            $data->jenis_kelamin_pengurus = $data->jenis_kelamin_pengurus;
        }else{
            $data->jenis_kelamin_pengurus = $request->jenis_kelamin_pengurus;
        }

        $data->nama_yayasan = $request->nama_yayasan;
        $data->alamat = $request->alamat;
        $data->no_telp = $request->no_telp;
        $data->tgl_berdiri = $request->tgl_berdiri;
        $data->visi = $request->visi;
        $data->misi = $request->misi;
        $data->tentang_yayasan = $request->tentang_yayasan;
        $data->nama_pengurus = $request->nama_pengurus;
        $data->alamat_pengurus = $request->alamat_pengurus;
        $data->no_telp_pengurus = $request->no_telp_pengurus;
        $data->update();

        if (Auth::user()->role == "superadmin") {
            return redirect()->route('yayasan.index');
        } else {
            return back();
        }
        
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $data = Yayasan::findOrfail($id);
        $data->delete();

        return redirect()->route('yayasan.index');
    }

    public function profile($id)
    {
        $data['yayasan'] = Yayasan::find($id);
        return view('backend.yayasan.profile', $data);
    }

    public function updateProfile(Request $request, $id)
    {
        dd($request);
        $data = Yayasan::findOrFail($id);

        if ($request->file('foto_yayasan') == "") {
            $data->foto_yayasan = $data->foto_yayasan;
        } else {
            $path = 'images';
            $file = $request->foto_yayasan;
            $extension = $file->getClientOriginalExtension();
            $fileName = rand(1111, 9999) . "." . $extension;
            $file->move($path, $fileName);

            $data->foto_yayasan = $fileName;
        }

        if ($request->file('foto_ktp_pengurus') == "") {
            $data->foto_ktp_pengurus = $data->foto_ktp_pengurus;
        } else {
            $path = 'images';
            $file = $request->foto_ktp_pengurus;
            $extension = $file->getClientOriginalExtension();
            $fileName = rand(1111, 9999) . "." . $extension;
            $file->move($path, $fileName);
            $data->foto_ktp_pengurus = $fileName;
        }

        if ($request->jenis_kelamin_pengurus == "") {
            $data->jenis_kelamin_pengurus = $data->jenis_kelamin_pengurus;
        } else {
            $data->jenis_kelamin_pengurus = $request->jenis_kelamin_pengurus;
        }

        $data->nama_yayasan = $request->nama_yayasan;
        $data->alamat = $request->alamat;
        $data->no_telp = $request->no_telp;
        $data->tgl_berdiri = $request->tgl_berdiri;
        $data->visi = $request->visi;
        $data->misi = $request->misi;
        $data->tentang_yayasan = $request->tentang_yayasan;
        $data->nama_pengurus = $request->nama_pengurus;
        $data->alamat_pengurus = $request->alamat_pengurus;
        $data->no_telp_pengurus = $request->no_telp_pengurus;
        $data->update();

        return redirect()->route('yayasan.index');
    }

    // For Expor Excel where ID selected
    public function export($id)
    {
        return Excel::download(new YayasanExport($id), 'yayasan.csv');
    }

    // For Export PDF where ID selected
    public function pdfDataYayasan($id)
    {
        $yayasan = Yayasan::where('id',$id)->get();

        $pdf = PDF::loadView('pdf.data-yayasan',['yayasan'=>$yayasan])->setPaper('A4','landscape');
        return $pdf->stream('data-yayasan.pdf');
        // return view('pdf.data-yayasan', ['yayasan' => $yayasan]);
    }

    public function pdfDataAnak($id)
    {
        $anak = DataAnak::where('id_yayasan', $id)->get();
        $get_yayasan = DataAnak::where('id_yayasan', $id)->get()->first();

        $pdf = PDF::loadView('pdf.data-anak-per-yayasan', ['anak' => $anak, 'judul' => $get_yayasan])->setPaper('A4', 'landscape');
        return $pdf->stream('data-anak.pdf');
        // return view('pdf.data-anak-per-yayasan', ['anak' => $anak,'judul' => $get_judul_yayasan]);
    }

    public function pdfVaksinasi($id)
    {
        $vaksinasi = Vaksinasi::where('id_yayasan', $id)->get();
        $get_yayasan = Vaksinasi::where('id_yayasan', $id)->get()->first();

        $pdf = PDF::loadView('pdf.vaksinasi-per-yayasan', ['vaksinasi' => $vaksinasi,'judul'=>$get_yayasan])->setPaper('A4', 'landscape');
        return $pdf->stream('vaksinasi.pdf');
    }
 
    public function pdfKesehatan($id)
    {
        $kesehatan = Kesehatan::where('id_yayasan', $id)->get();
        $get_yayasan = Kesehatan::where('id_yayasan', $id)->get()->first();

        $pdf = PDF::loadView('pdf.kesehatan-per-yayasan', ['kesehatan' => $kesehatan,'judul'=>$get_yayasan ])->setPaper('A4', 'landscape');
        return $pdf->stream('kesehatan.pdf');
    }
}

resources/views/backend/yayasan/index.blade.php
@extends('backend.layouts.app')

@section('content')
<div class="page-wrapper">
    <!-- Bread crumb -->
    <div class="row page-titles">
        <div class="col-md-5 align-self-center">
            <h3 class="text-primary">Data Yayasan</h3>
        </div>
        <div class="col-md-7 align-self-center">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
                <li class="breadcrumb-item active">Data Yayasan</li>
            </ol>
        </div>
    </div>
    <!-- End Bread crumb -->
    <!-- Container fluid  -->
    <div class="container-fluid">
        <!-- Start Page Content -->
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <div class="table-responsive m-t-0">
                            <a href="{{ route('yayasan.create')}}" class="btn btn-info" name="button">Tambah Yayasan</a>
                            <table id="example23" class="display nowrap table table-hover table-striped table-bordered" cellspacing="0" width="100%">
                                <thead>
                                    <tr>
                                        <th>Nama Yayasan</th>
                                        <th>Foto Yayasan</th>
                                        <th>No Telp</th>
                                        <th>Tgl Berdiri</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($datas as $data)
                                    <tr>
                                        <td style="text-decoration:underline;"><a href="{{ route('yayasan.show',$data->id) }}"> {{ $data->nama_yayasan }}</a></td>
                                        <td>
                                            @if($data->foto_yayasan)
                                            <img src="{{asset('images/'.$data->foto_yayasan)}}" alt="logo" height="50" width="50" style="display:block;margin-left:auto;margin-right:auto;">
                                            @else
                                            <p>Tidak ada gambar</p>
                                            @endif
                                        </td>
                                        <td>{{ $data->no_telp }}</td>
                                        <td>{{ $data->tgl_berdiri }}</td>
                                        <td style="display:inline-flex;margin-left:17%;">
                                            <a href="{{ route('yayasan.edit', $data->id) }}" class="btn btn-warning" name="button"><i class="fa fa-pencil" aria-hidden="true"></i></a>&nbsp;
                                            <!-- <button class="btn btn-danger btn sweet-confirm" form="{{ $data->id }}"><i class="fa fa-trash-o" aria-hidden="true"> </i></button> -->
                                            <form action="{{ route('yayasan.destroy',$data->id) }}" onsubmit="return confirm('Yakin ingin menghapus data ini?');" method="POST">
                                                <input type="hidden" name="_method" value="DELETE">
                                                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                                <button type="submit" class="btn btn-danger btn sweet-confirm"><i class="fa fa-trash-o" aria-hidden="true"> </i></button>
                                            </form>
                                        </td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End PAge Content -->
    </div>
</div>
@endsection

resources/views/backend/yayasan/profile.blade.php
@extends('backend.layouts.app')
@section('content')
<style>
    .form-control::-webkit-input-placeholder {
        font-size: 14px;
        color: darkgrey;
    }

    .form-control::-moz-input-placeholder {
        color: darkgrey;
    }

    .form-control:-ms-input-placeholder {
        color: darkgrey;
    }

    textarea {
        width: 100%;
        height: 80px;
    }
</style>
<div class="page-wrapper">
    <!-- Bread crumb -->
    <div class="row page-titles">
        <div class="col-md-5 align-self-center">
            <h3 class="text-primary">Setting Profile</h3>
        </div>
        <div class="col-md-7 align-self-center">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
                <li class="breadcrumb-item active">Setting Profile</li>
            </ol>
        </div>
    </div>
    <!-- End Bread crumb -->
    <!-- Container fluid  -->
    <div class="container-fluid">
        <!-- Start Page Content -->
        <div class="row">
            <!-- Column -->
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">
                        <div class="card-two">
                            <div style="text-align:center;">
                                @if($yayasan->foto_yayasan == "")
                                <img src="{{ asset('/images/placeholder.png')}}" id="img_preview" alt="your image" height="200" width="200"><br>
                                @else
                                <img src="{{ asset('/images/'.$yayasan->foto_yayasan)}}" id="img_preview" height="200" width="200"><br>
                                @endif

                            </div>
                            <h3>{{ $yayasan->nama_yayasan }}</h3>
                            <div class="desc">
                                {{ strip_tags($yayasan->visi) }}
                            </div>
                            <div class="contacts">
                                <a href=""><i class="fa fa-plus"></i></a>
                                <a href=""><i class="fa fa-whatsapp"></i></a>
                                <a href=""><i class="fa fa-envelope"></i></a>
                                <div class="clear"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Column -->
            <!-- Column -->
            <div class="col-lg-12">
                <div class="card">
                    <!-- Nav tabs -->
                    <ul class="nav nav-tabs profile-tab" role="tablist">
                        <li class="nav-item"> <a class="nav-link active" data-toggle="tab" href="#settings" role="tab">Profile Yayasan</a> </li>
                        <li class="nav-item"> <a class="nav-link" data-toggle="tab" href="#pengurus" role="tab">Profile Pengurus</a> </li>
                    </ul>
                    <!-- Tab panes -->
                    <form class="form-horizontal form-material" action="{{ route('yayasan.update',$yayasan->id) }}" enctype="multipart/form-data" method="post">
                        <div class="tab-content">
                            @csrf
                            {{ method_field('PUT') }}

                            <div class="tab-pane active" id="settings" role="tabpanel">
                                <div class="card-body">
                                    <div class="form-group">
                                        <label class="col-md-12">Nama Yayasan</label>
                                        <div class="col-md-12">
                                            <input type="text" name="nama_yayasan" class="form-control form-control-line" value="{{ $yayasan->nama_yayasan }}">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label for="example-email" class="col-md-12">No telp</label>
                                        <div class="col-md-12">
                                            <input type="text" name="no_telp" class="form-control form-control-line" value="{{ $yayasan->no_telp }}">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-md-12">Tanggal Berdiri</label>
                                        <div class="col-md-12">
                                            <input type="date" name="tgl_berdiri" class="form-control form-control-line" value="{{ $yayasan->tgl_berdiri }}">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-md-12">Alamat</label>
                                        <div class="col-md-12">
                                            <textarea rows="10" name="alamat" cols="124" style="border-color:lightgrey;">{{ $yayasan->alamat }}</textarea>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-md-12">Visi</label>
                                        <div class="col-md-12">
                                            <textarea id="visi" name="visi" class="form-control form-control-line">{{ $yayasan->visi }}</textarea>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-md-12">Misi</label>
                                        <div class="col-md-12">
                                            <textarea id="misi" name="misi" class="form-control form-control-line">{{ $yayasan->misi }}</textarea>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-md-12">Tentang Yayasan</label>
                                        <div class="col-md-12">
                                            <textarea id="tentang" name="tentang_yayasan" class="form-control form-control-line">{{ $yayasan->tentang_yayasan }}</textarea>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-md-12">Upload Foto</label>
                                        <div class="col-md-12">
                                            <input type="file" id="img_upload" name="foto_yayasan" value="{{ $yayasan->foto_yayasan }}">
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="tab-pane active" id="pengurus" role="tabpanel">
                                <div class="card-body">
                                    <div class="basic-elements">
                                        <div class="row">
                                            <div class="col-lg-6">
                                                <div class="form-group">
                                                    <label>Nama Pengurus<span style="color:red;"> *</span></label>
                                                    <input type="text" name="nama_pengurus" class="form-control" value="{{ $yayasan->nama_pengurus }}" placeholder="Nama Pengurus" required>
                                                    <p style="color:red;font-size:13px;">
                                                        @if($errors->has('nama_pengurus'))
                                                        <i class="fa fa-exclamation-circle"></i> {{$errors->first('nama_pengurus')}}
                                                        @endif
                                                    </p>
                                                </div>

                                                <label>Foto KTP<span style="color:red;"> *</span></label>
                                                <div class="form-group dropzone">
                                                    <input class="form-control" name="foto_ktp_pengurus" type="file" value="{{ $yayasan->foto_ktp_pengurus }}" multiple />
                                                </div>
                                                <p style="color:red;font-size:13px;">
                                                    @if($errors->has('foto_ktp_pengurus'))
                                                    <i class="fa fa-exclamation-circle"></i> {{$errors->first('foto_ktp_pengurus')}}
                                                    @endif
                                                </p>
                                            </div>
                                            <div class="col-lg-6">
                                                <div class="form-group">
                                                    <label>No Telp<span style="color:red;"> *</span></label>
                                                    <input type="number" name="no_telp_pengurus" class="form-control" value="{{ $yayasan->no_telp_pengurus }}" placeholder="No Telp" required>
                                                    <p style="color:red;font-size:13px;">
                                                        @if($errors->has('no_telp_pengurus'))
                                                        <i class="fa fa-exclamation-circle"></i> {{$errors->first('no_telp_pengurus')}}
                                                        @endif
                                                    </p>
                                                </div>
                                                <div class="form-group">
                                                    <label>Jenis Kelamin<span style="color:red;"> *</span></label>
                                                    <select class="form-control" name="jenis_kelamin_pengurus" value="{{ $yayasan->jenis_kelamin_pengurus }}">
                                                        <option selected="true" disabled="disabled" value="{{ $yayasan->jenis_kelamin_pengurus }}">{{ $yayasan->jenis_kelamin_pengurus }}</option>
                                                        <option value="Laki-Laki">Laki-Laki</option>
                                                        <option value="Perempuan">Perempuan</option>
                                                    </select>
                                                    <p style="color:red;font-size:13px;">
                                                        @if($errors->has('jenis_kelamin'))
                                                        <i class="fa fa-exclamation-circle"></i> {{$errors->first('jenis_kelamin')}}
                                                        @endif
                                                    </p>
                                                </div>
                                                <div class="form-group">
                                                    <label>Alamat<span style="color:red;"> *</span></label>
                                                    <textarea required="required" id="alamat" style="border-color:lightgrey;" name="alamat_pengurus" rows="3" cols="58">{{ $yayasan->alamat_pengurus }}</textarea>
                                                    <p style="color:red;font-size:13px;">
                                                        @if($errors->has('alamat_pengurus'))
                                                        <i class="fa fa-exclamation-circle"></i> {{$errors->first('alamat_pengurus')}}
                                                        @endif
                                                    </p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-sm-12">
                                    <button class="btn btn-success">Update Profile</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <!-- Column -->
        </div>

        <!-- End PAge Content -->
    </div>
</div>
<script type="text/javascript">
    function readUrl(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function(e) {
                $('#img_preview').attr('src', e.target.result)
                ''
            }

            reader.readAsDataURL(input.files[0]);
        }
    }

    $('#img_upload').change(function() {
        readUrl(this);
    });
</script>
@endsection