routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// Auth::routes();

Route::get('/&&anakita-login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('/&&anakita-login', 'Auth\LoginController@login');
Route::post('/&&anakita-logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
Route::get('/&&anakita-register', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('/&&anakita-register', 'Auth\RegisterController@register');

Route::get('/&&anakita-password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('/&&anakita-password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('/&&anakita-password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('/&&anakita-password/reset', 'Auth\ResetPasswordController@reset')->name('password.update');




Route::get('/home', 'HomeController@index')->name('home');
Route::resource('/data-anak', 'DataAnakController');
Route::resource('/data-visual', 'DataVisualController');
Route::resource('/riwayat-vaksinasi', 'VaksinasiController');
Route::resource('/riwayat-kesehatan', 'KesehatanController');
Route::resource('/yayasan', 'YayasanController');
Route::resource('/user', 'UsersController');
Route::resource('/daftar-penyakit', 'DaftarPenyakitController');
// Route::resource('/log', 'AuditController');
    
Route::get('/profile/{id}','YayasanController@profile')->name('profile');
Route::post('/profile/{id}','YayasanController@updateProfile')->name('updateProfile');
Route::post('/data-anak/cari','DataAnakController@cari')->name('cariAnak');
Route::get('/log','HomeController@getAudit');


// Route for Excel and PDF Report
Route::get('excel/vaksinasi/{id}','VaksinasiController@export')->name('export.vaksinasi');
Route::get('excel/kesehatan/{id}','KesehatanController@export')->name('export.kesehatan');
Route::get('excel/data-anak/{id}','DataAnakController@export')->name('export.data-anak');
Route::get('excel/yayasan/{id}','YayasanController@export')->name('export.data-yayasan');

Route::get('pdf/vaksinasi/{id}', 'VaksinasiController@pdf')->name('pdf.vaksinasi');
Route::get('pdf/kesehatan/{id}', 'KesehatanController@pdf')->name('pdf.kesehatan');

Route::get('pdf/data-anak/{id}', 'DataAnakController@pdfDataAnak')->name('pdf.data-anak');
Route::get('pdf/data-anak/vaksinasi/{id}', 'DataAnakController@pdfVaksinasi')->name('pdf.data-anak.vaksinasi');
Route::get('pdf/data-anak/kesehatan/{id}', 'DataAnakController@pdfKesehatan')->name('pdf.data-anak.kesehatan');

Route::get('pdf/yayasan/{id}', 'YayasanController@pdfDataYayasan')->name('pdf.data-yayasan');
Route::get('pdf/yayasan/data-anak/{id}', 'YayasanController@pdfDataAnak')->name('pdf.data-yayasan.data-anak');
Route::get('pdf/yayasan/vaksinasi/{id}', 'YayasanController@pdfVaksinasi')->name('pdf.data-yayasan.vaksinasi');
Route::get('pdf/yayasan/kesehatan/{id}', 'YayasanController@pdfKesehatan')->name('pdf.data-yayasan.kesehatan');

resources/views/backend/riwayat-vaksinasi/create.blade.php
@extends('backend.layouts.app')

@section('content')
<style>
    .form-control::-webkit-input-placeholder {
        font-size: 14px;
        color: darkgrey;
    }

    .form-control::-moz-input-placeholder {
        color: darkgrey;
    }

    .form-control:-ms-input-placeholder {
        color: darkgrey;
    }

    textarea {
        width: 100%;
        height: 110px;
    }
</style>
<div class="page-wrapper">
    <!-- Bread crumb -->
    <div class="row page-titles">
        <div class="col-md-5 align-self-center">
            <h3 class="text-primary">Vaksinasi</h3>
        </div>
        <div class="col-md-7 align-self-center">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="javascript:void(0)">Tambah</a></li>
                <li class="breadcrumb-item active">Vaksinasi</li>
            </ol>
        </div>
    </div>
    <!-- End Bread crumb -->
    <!-- Container fluid  -->
    <div class="container-fluid">
        <!-- Start Page Content -->
        <!-- /# row -->
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-title">
                        <h4>Tambah vaksinasi</h4>

                    </div>
                    <div class="card-body">
                        <div class="basic-elements">
                            <form action="{{ route('riwayat-vaksinasi.store') }}" enctype="multipart/form-data" method="post">
                                @csrf
                                <div class="row">
                                    <div class="col-lg-6">
                                        <div class="form-group">
                                            <label>Nama Anak<span style="color:red;"> *</span></label>
                                            <select class="js-example-basic-single form-control " name="id_anak" style="width:100%;" required>
                                                <option selected="true" disabled="disabled" value="{{ old('id_anak') }}">Pilih</option>
                                                @foreach($datas as $data)
                                                <option value="{{ $data->id }}">{{ $data->nama_anak }}</option>
                                                @endforeach
                                            </select>
                                            <p style="color:red;font-size:13px;">
                                                @if($errors->has('id_anak'))
                                                <i class="fa fa-exclamation-circle"></i> {{$errors->first('id_anak')}}
                                                @endif
                                            </p>
                                        </div>

                                        @if(Auth::user()->role == "superadmin")
                                        <div class="form-group">
                                            <label>Nama Yayasan<span style="color:red;"> *</span></label>
                                            <select class="js-example-basic-single form-control" name="id_yayasan" style="width:100%;" required>
                                                <option selected="true" disabled="disabled" value="{{ old('id_yayasan') }}">Pilih</option>
                                                @foreach($yayasan as $data)
                                                <option value="{{ $data->id }}">{{ $data->nama_yayasan }}</option>
                                                @endforeach
                                            </select>
                                            <p style="color:red;font-size:13px;">
                                                @if($errors->has('id_yayasan'))
                                                <i class="fa fa-exclamation-circle"></i> {{$errors->first('id_yayasan')}}
                                                @endif
                                            </p>
                                        </div>
                                        @else
                                        <input type="hidden" name="id_yayasan" value="{{ Auth::user()->id_yayasan }}">
                                        @endif

                                        <div class="form-group">
                                            <label>Pemberi Vaksin<span style="color:red;"> *</span></label>
                                            <input type="text" name="pemberi_vaksinasi" class="form-control" value="{{ old('pemberi_vaksinasi') }}" placeholder="Pemberi Vaksin" required>
                                            <p style="color:red;font-size:13px;">
                                                @if($errors->has('pemberi_vaksinasi'))
                                                <i class="fa fa-exclamation-circle"></i> {{$errors->first('pemberi_vaksinasi')}}
                                                @endif
                                            </p>
                                        </div>
                                    </div>
                                    <div class="col-lg-6">
                                        <div class="form-group">
                                            <label>Posyandu/Rumah Sakit<span style="color:red;"> *</span></label>
                                            <input type="text" name="tempat_vaksinasi" class="form-control" value="{{ old('tempat_vaksinasi') }}" placeholder="Nama Tempat" required>
                                            <p style="color:red;font-size:13px;">
                                                @if($errors->has('tempat_vaksinasi'))
                                                <i class="fa fa-exclamation-circle"></i> {{$errors->first('tempat_vaksinasi')}}
                                                @endif
                                            </p>
                                        </div>
                                        <div class="form-group">
                                            <label>Alamat tempat di vaksin<span style="color:red;"> *</span></label>
                                            <textarea style="border-color:lightgrey;" name="alamat_tempat_vaksinasi" required></textarea>
                                            <p style="color:red;font-size:13px;">
                                                @if($errors->has('alamat_tempat_vaksinasi'))
                                                <i class="fa fa-exclamation-circle"></i> {{$errors->first('alamat_tempat_vaksinasi')}}
                                                @endif
                                            </p>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-lg-12">
                                        <hr class="style">
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-lg-6">
                                        <div class="form-group">
                                            <label>Jenis Vaksinasi<span style="color:red;"> *</span></label><br>
                                            <input id="wajib" type="radio" name="jenis_vaksinasi" value="Wajib" required> Wajib &nbsp;
                                            <input id="tambahan" type="radio" name="jenis_vaksinasi" value="Tambahan"> Tambahan
                                        </div>
                                        <div class="form-group">
                                            <label>Vaksinasi Wajib</label>
                                            <select id="vaksinasi_wajib" class="js-example-basic-single form-control" name="vaksinasi_wajib" disabled>
                                                <option value="" selected disabled>Pilih</option>
                                                <option value="Hepatitis B">Hepatitis B</option>
                                                <option value="Polio">Polio</option>
                                                <option value="BCG">BCG</option>
                                                <option value="Campak">Campak</option>
                                                <option value="Pentavalen">Pentavalen (DPT-HB-HiB)</option>
                                            </select>
                                            <p style="color:red;font-size:13px;">
                                                @if($errors->has('id_yayasan'))
                                                <i class="fa fa-exclamation-circle"></i> {{$errors->first('id_yayasan')}}
                                                @endif
                                            </p>
                                        </div>
                                        <div class="form-group">
                                            <label>Vaksinasi Tambahan</label>
                                            <select id="vaksinasi_tambahan" class="js-example-basic-single form-control" name="vaksinasi_tambahan" disabled>
                                                <option value="" selected disabled>Pilih</option>
                                                <option value="Pneumokokus Conjugate Vaccine">Pneumokokus Conjugate Vaccine(PCV)</option>
                                                <option value="Varisela">Varisela</option>
                                                <option value="Influenza">Influenza</option>
                                                <option value="Hepatitis A">Hepatitis A</option>
                                                <option value="HPV">HPV (Human Papiloma Virus)</option>
                                            </select>
                                            <p style="color:red;font-size:13px;">
                                                @if($errors->has('id_yayasan'))
                                                <i class="fa fa-exclamation-circle"></i> {{$errors->first('id_yayasan')}}
                                                @endif
                                            </p>
                                        </div>
                                        <div class="form-group">
                                            <label>Catatan</label>
                                            <textarea style="border-color:lightgrey;" name="catatan"></textarea>
                                            <p style="color:red;font-size:13px;">
                                                @if($errors->has('catatan'))
                                                <i class="fa fa-exclamation-circle"></i> {{$errors->first('catatan')}}
                                                @endif
                                            </p>
                                        </div>
                                    </div>
                                    <div class="col-lg-6">
                                        <div class="form-group">
                                            <input type="hidden" name="" class="form-control" value="" placeholder="">
                                        </div><br><br>
                                        <div class="form-group">
                                            <label>&nbsp;</label>
                                            <input type="date" id="tgl_vaksinasi_wajib" name="tgl_vaksinasi_wajib" class="form-control" value="{{ old('tgl_vaksinasi_wajib') }}" placeholder="Terakhir Periksa" disabled>
                                            <p style="color:red;font-size:13px;">
                                                @if($errors->has('tgl_vaksinasi_wajib'))
                                                <i class="fa fa-exclamation-circle"></i> {{$errors->first('tgl_vaksinasi_wajib')}}
                                                @endif
                                            </p>
                                        </div><br>
                                        <div class="form-group">
                                            <input type="date" id="tgl_vaksinasi_tambahan" name="tgl_vaksinasi_tambahan" class="form-control" value="{{ old('tgl_vaksinasi_tambahan') }}" placeholder="Terakhir Periksa" disabled>
                                            <p style="color:red;font-size:13px;">
                                                @if($errors->has('tgl_vaksinasi_tambahan'))
                                                <i class="fa fa-exclamation-circle"></i> {{$errors->first('tgl_vaksinasi_tambahan')}}
                                                @endif
                                            </p>
                                        </div>
                                    </div>
                                </div>
                                <div class="dt-buttons">
                                    <div class="sweetalert m-t-15">
                                        <button class="btn btn-info btn sweet-success" name="save" id="save" type="submit">Submit</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End PAge Content -->
    </div>
</div>
@endsection

resources/views/backend/riwayat-vaksinasi/index.blade.php
@extends('backend.layouts.app')

@section('content')
<div class="page-wrapper">
    <!-- Bread crumb -->
    <div class="row page-titles">
        <div class="col-md-5 align-self-center">
            <h3 class="text-primary">Data Vaksinasi</h3>
        </div>
        <div class="col-md-7 align-self-center">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
                <li class="breadcrumb-item active">Data Vaksinasi</li>
            </ol>
        </div>
    </div>
    <!-- End Bread crumb -->
    <!-- Container fluid  -->
    <div class="container-fluid">
        <!-- Start Page Content -->
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <div class="table-responsive m-t-0">
                            <a href="{{ route('riwayat-vaksinasi.create')}}" class="btn btn-info" name="button">Tambah Vaksinasi</a>
                            <table id="example23" class="display nowrap table table-hover table-striped table-bordered" cellspacing="0" width="100%">
                                <thead>
                                    <tr>
                                        <th>Nama</th>
                                        <th>Pemberi Imunisasi</th>
                                        <th>Tempat Vaksinasi</th>
                                        <th>Vaksinasi Wajib</th>
                                        <th>Vaksinasi Tambahan</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($datas as $data)
                                    <tr>
                                        <td style="text-decoration:underline;"><a href="{{ route('riwayat-vaksinasi.show',$data->id) }}"> {{ $data->dataAnak->nama_anak }}</a></td>
                                        <td>{{ $data->pemberi_vaksinasi }}</td>
                                        <td>{{ $data->tempat_vaksinasi }}</td>

                                        @if($data->vaksinasi_wajib == "Pentavalen")
                                        <td>{{ $data->vaksinasi_wajib }} (DPT-HB-HiB)</td>
                                        @else
                                        <td>{{ $data->vaksinasi_wajib }}</td>
                                        @endif

                                        @if($data->vaksinasi_tambahan == "HPV")
                                        <td>{{ $data->vaksinasi_tambahan }} (Human Papiloma Virus)</td>
                                        @else
                                        <td>{{ $data->vaksinasi_tambahan }}</td>
                                        @endif
                                        <td style="display:inline-flex;margin-left:10%;">
                                            <a href="{{ route('riwayat-vaksinasi.edit', $data->id) }}" class="btn btn-warning" name="button"><i class="fa fa-pencil" aria-hidden="true"></i></a>&nbsp;
                                            <!-- <button class="btn btn-danger btn sweet-confirm" form="{{ $data->id }}"><i class="fa fa-trash-o" aria-hidden="true"> </i></button> -->
                                            <form action="{{ route('riwayat-vaksinasi.destroy',$data->id) }}" onsubmit="return confirm('Yakin ingin menghapus data ini?');" method="POST">
                                                <input type="hidden" name="_method" value="DELETE">
                                                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                                <button type="submit" class="btn btn-danger btn sweet-confirm"><i class="fa fa-trash-o" aria-hidden="true"> </i></button>
                                            </form>
                                        </td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End PAge Content -->
    </div>
</div>
@endsection

resources/views/backend/riwayat-vaksinasi/show.blade.php
 @extends('backend.layouts.app')

 @section('content')
 <div class="page-wrapper">
     <!-- Bread crumb -->
     <div class="row page-titles">
         <div class="col-md-5 align-self-center">
             <h3 class="text-primary">Data Vaksinasi</h3>
         </div>
         <div class="col-md-7 align-self-center">
             <ol class="breadcrumb">
                 <li class="breadcrumb-item"><a href="javascript:void(0)">Data Vaksinasi</a></li>
                 <li class="breadcrumb-item active">Show</li>
             </ol>
         </div>
     </div>
     <!-- End Bread crumb -->
     <!-- Container fluid  -->
     <div class="container-fluid">
         <!-- Start Page Content -->
         <!-- /# row -->
         <div class="row">
             <div class="col-lg-12">
                 <div class="card pink">
                     <div class="card-title">
                         <h2 style="text-decoration:underline;" class="pink-name">Info Lengkap Vaksinasi</h2>
                         <a href="{{ route('export.vaksinasi',$vaksinasi->id) }}" class="btn float-right" name="button" style="margin-left:1%;background-color:white;color:#e9748a;">Excel</a>
                         <a href="{{ route('pdf.vaksinasi',$vaksinasi->id) }}" class="btn float-right" name="button" style="background-color:white;color:#e9748a;">PDF</a>

                     </div>
                     <div class="card-body">
                         <div class="basic-elements">
                             <div class="card">
                                 <div class="row">
                                     <div class="col-lg-6">
                                         <div class="form-group">
                                             <label style="font-weight:bold;">Nama:</label><br>
                                             <h4>{{ $vaksinasi->dataAnak->nama_anak }}</h4>
                                         </div>
                                         <div class="form-group">
                                             <label style="font-weight:bold;">Jenis Imunisasi:</label><br>
                                             <h4>{{ $vaksinasi->jenis_vaksinasi }}</h4>
                                         </div>
                                         <div class="form-group">
                                             <label style="font-weight:bold;">Alamat Tempat Vaksinasi:</label><br>
                                             <h4>{{ $vaksinasi->alamat_tempat_vaksinasi }}</h4>
                                         </div>
                                     </div>
                                     <div class="col-lg-6">
                                         <div class="form-group">
                                             <label style="font-weight:bold;">Pemberi Imunisasi:</label><br>
                                             <h4>{{ $vaksinasi->pemberi_vaksinasi }}</h4>
                                         </div>
                                         <div class="form-group">
                                             <label style="font-weight:bold;">Tempat Vaksinasi:</label><br>
                                             <h4>{{ $vaksinasi->tempat_vaksinasi }}</h4>
                                         </div>

                                     </div>
                                 </div>
                                 <div class="row">
                                     <div class="col-lg-12">
                                         <hr class="style">
                                     </div>
                                 </div>
                                 <div class="row">
                                     <div class="col-lg-6">
                                         <div class="form-group">
                                             <h2 style="text-decoration:underline;">Jenis Vaksinasi</h2>
                                         </div>
                                         <div class="form-group">
                                             <label style="font-weight:bold;">Vaksinasi Wajib:</label><br>
                                             <h4>{{ $vaksinasi->vaksinasi_wajib }}</h4>
                                         </div>
                                         <div class="form-group" style="margin-bottom:10%;">
                                             <label style="font-weight:bold;">Tgl Pemberian Vaksinasi Wajib:</label><br>
                                             <h4>{{ $vaksinasi->tgl_vaksinasi_wajib }}</h4>
                                         </div>
                                     </div>
                                     <div class="col-lg-6">
                                         <div class="form-group">
                                             <h2>&nbsp;</h2>
                                         </div>
                                         <div class="form-group">
                                             <label style="font-weight:bold;">Vaksinasi Tambahan:</label><br>
                                             <h4>{{ $vaksinasi->vaksinasi_tambahan }}</h4>
                                         </div>
                                         <div class="form-group" style="margin-bottom:10%;">
                                             <label style="font-weight:bold;">Tgl Pemberian Vaksinasi Tambahan:</label><br>
                                             <h4>{{ $vaksinasi->tgl_vaksinasi_tambahan }}</h4>
                                         </div>
                                     </div>
                                 </div>
                                 <div class="row">
                                     <div class="col-lg-12">
                                         <hr class="style">
                                     </div>
                                 </div>
                                 <div class="row">
                                     <div class="col-lg-6">
                                         <div class="form-group" style="margin-bottom:10%;">
                                             <label style="font-weight:bold;">Catata:</label><br>
                                             <h4>{{ $vaksinasi->catatan }}</h4>
                                         </div>
                                     </div>
                                 </div>
                                 <div class="dt-buttons">
                                     <div class="sweetalert m-t-15">
                                         <a href="{{ route('riwayat-vaksinasi.edit', $vaksinasi->id) }}" class="btn btn-warning btn-md m-b-10 m-l-5" name="button">Edit</a>
                                         <a href="{{ route('riwayat-vaksinasi.index') }}" class="btn btn-primary btn-md m-b-10 m-l-5" name="button">Back</a>
                                     </div>
                                 </div>
                             </div>
                         </div>
                     </div>
                 </div>
             </div>
         </div>
         <!-- End PAge Content -->
     </div>
 </div>
 @endsection