routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// Auth::routes();

Route::get('/&&anakita-login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('/&&anakita-login', 'Auth\LoginController@login');
Route::post('/&&anakita-logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
Route::get('/&&anakita-register', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('/&&anakita-register', 'Auth\RegisterController@register');

Route::get('/&&anakita-password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('/&&anakita-password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('/&&anakita-password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('/&&anakita-password/reset', 'Auth\ResetPasswordController@reset')->name('password.update');




Route::get('/home', 'HomeController@index')->name('home');
Route::resource('/data-anak', 'DataAnakController');
Route::resource('/data-visual', 'DataVisualController');
Route::resource('/riwayat-vaksinasi', 'VaksinasiController');
Route::resource('/riwayat-kesehatan', 'KesehatanController');
Route::resource('/yayasan', 'YayasanController');
Route::resource('/user', 'UsersController');
Route::resource('/daftar-penyakit', 'DaftarPenyakitController');
// Route::resource('/log', 'AuditController');
    
Route::get('/profile/{id}','YayasanController@profile')->name('profile');
Route::post('/profile/{id}','YayasanController@updateProfile')->name('updateProfile');
Route::post('/data-anak/cari','DataAnakController@cari')->name('cariAnak');
Route::get('/log','HomeController@getAudit');


// Route for Excel and PDF Report
Route::get('excel/vaksinasi/{id}','VaksinasiController@export')->name('export.vaksinasi');
Route::get('excel/kesehatan/{id}','KesehatanController@export')->name('export.kesehatan');
Route::get('excel/data-anak/{id}','DataAnakController@export')->name('export.data-anak');
Route::get('excel/yayasan/{id}','YayasanController@export')->name('export.data-yayasan');

Route::get('pdf/vaksinasi/{id}', 'VaksinasiController@pdf')->name('pdf.vaksinasi');
Route::get('pdf/kesehatan/{id}', 'KesehatanController@pdf')->name('pdf.kesehatan');

Route::get('pdf/data-anak/{id}', 'DataAnakController@pdfDataAnak')->name('pdf.data-anak');
Route::get('pdf/data-anak/vaksinasi/{id}', 'DataAnakController@pdfVaksinasi')->name('pdf.data-anak.vaksinasi');
Route::get('pdf/data-anak/kesehatan/{id}', 'DataAnakController@pdfKesehatan')->name('pdf.data-anak.kesehatan');

Route::get('pdf/yayasan/{id}', 'YayasanController@pdfDataYayasan')->name('pdf.data-yayasan');
Route::get('pdf/yayasan/data-anak/{id}', 'YayasanController@pdfDataAnak')->name('pdf.data-yayasan.data-anak');
Route::get('pdf/yayasan/vaksinasi/{id}', 'YayasanController@pdfVaksinasi')->name('pdf.data-yayasan.vaksinasi');
Route::get('pdf/yayasan/kesehatan/{id}', 'YayasanController@pdfKesehatan')->name('pdf.data-yayasan.kesehatan');

app/Models/DaftarPenyakit.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class DaftarPenyakit extends Model
{
    protected $fillable = ['nama_penyakit','deskripsi'];
}

app/Http/Controllers/DaftarPenyakitController.php
<?php

namespace App\Http\Controllers;

use App\Models\DaftarPenyakit;
use Illuminate\Http\Request;

class DaftarPenyakitController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['penyakit'] = DaftarPenyakit::all();
        return view('backend.daftar-penyakit.index',$data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.daftar-penyakit.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $input['nama_penyakit'] = $request->nama_penyakit;
        $input['deskripsi'] = $request->deskripsi;
        DaftarPenyakit::create($input);

        return redirect()->route('daftar-penyakit.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['penyakit'] = DaftarPenyakit::findOrFail($id);
        return view('backend.daftar-penyakit.edit', $data);
        
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = DaftarPenyakit::find($id);
        $data->nama_penyakit = $request->nama_penyakit;
        $data->deskripsi = $request->deskripsi;
        $data->update();
        return redirect()->route('daftar-penyakit.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        DaftarPenyakit::destroy($id);
        return redirect()->route('daftar-penyakit.index');
    }
}

resources/views/backend/daftar-penyakit/create.blade.php
@extends('backend.layouts.app')

@section('content')
<style>
    .form-control::-webkit-input-placeholder {
        font-size: 14px;
        color: darkgrey;
    }

    .form-control::-moz-input-placeholder {
        color: darkgrey;
    }

    .form-control:-ms-input-placeholder {
        color: darkgrey;
    }
</style>
<div class="page-wrapper">
    <!-- Bread crumb -->
    <div class="row page-titles">
        <div class="col-md-5 align-self-center">
            <h3 class="text-primary">User</h3>
        </div>
        <div class="col-md-7 align-self-center">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="javascript:void(0)">Tambah</a></li>
                <li class="breadcrumb-item active">User</li>
            </ol>
        </div>
    </div>
    <!-- End Bread crumb -->
    <!-- Container fluid  -->
    <div class="container-fluid">
        <!-- Start Page Content -->
        <!-- /# row -->
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-title">
                        <h4>Tambah Penyakit</h4>

                    </div>
                    <div class="card-body">
                        <div class="basic-elements">
                            <form action="{{ route('daftar-penyakit.store') }}" enctype="multipart/form-data" method="post">
                                @csrf
                                <div class="row">
                                    <div class="col-lg-6">
                                        <div class="form-group">
                                            <label>Nama<span style="color:red;"> *</span></label>
                                            <input type="text" name="nama_penyakit" class="form-control" value="{{ old('nama_penyakit') }}" placeholder="Nama Penyakit" required>
                                            <p style="color:red;font-size:13px;">
                                                @if($errors->has('nama_penyakit'))
                                                <i class="fa fa-exclamation-circle"></i> {{$errors->first('nama_penyakit')}}
                                                @endif
                                            </p>
                                        </div>
                                        <label>Deskripsi<span style="color:red;"> *</span></label>
                                        <div class="form-group">
                                            <textarea style="border-color:lightgrey;" name="deskripsi" cols="48" rows="5" required></textarea>
                                            <p style="color:red;font-size:13px;">
                                                @if($errors->has('deskripsi'))
                                                <i class="fa fa-exclamation-circle"></i> {{$errors->first('deskripsi')}}
                                                @endif
                                            </p>
                                        </div>
                                    </div>
                                </div>
                                <div class="dt-buttons">
                                    <div class="sweetalert m-t-15">
                                        <button class="btn btn-info btn sweet-success" type="submit">Submit</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End PAge Content -->
    </div>
</div>
@endsection

resources/views/backend/daftar-penyakit/edit.blade.php
@extends('backend.layouts.app')

@section('content')
<style>
    .form-control::-webkit-input-placeholder {
        font-size: 14px;
        color: darkgrey;
    }

    .form-control::-moz-input-placeholder {
        color: darkgrey;
    }

    .form-control:-ms-input-placeholder {
        color: darkgrey;
    }
</style>
<div class="page-wrapper">
    <!-- Bread crumb -->
    <div class="row page-titles">
        <div class="col-md-5 align-self-center">
            <h3 class="text-primary">User</h3>
        </div>
        <div class="col-md-7 align-self-center">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="javascript:void(0)">Tambah</a></li>
                <li class="breadcrumb-item active">User</li>
            </ol>
        </div>
    </div>
    <!-- End Bread crumb -->
    <!-- Container fluid  -->
    <div class="container-fluid">
        <!-- Start Page Content -->
        <!-- /# row -->
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-title">
                        <h4>Tambah Penyakit</h4>

                    </div>
                    <div class="card-body">
                        <div class="basic-elements">
                            <form action="{{ route('daftar-penyakit.update',$penyakit->id) }}" enctype="multipart/form-data" method="post">
                                @csrf
                                {{ method_field('PUT') }}
                                <div class="row">
                                    <div class="col-lg-6">
                                        <div class="form-group">
                                            <label>Nama<span style="color:red;"> *</span></label>
                                            <input type="text" name="nama_penyakit" class="form-control" value="{{ $penyakit->nama_penyakit }}" placeholder="Nama Penyakit" required>
                                            <p style="color:red;font-size:13px;">
                                                @if($errors->has('nama_penyakit'))
                                                <i class="fa fa-exclamation-circle"></i> {{$errors->first('nama_penyakit')}}
                                                @endif
                                            </p>
                                        </div>
                                        <label>Deskripsi<span style="color:red;"> *</span></label>
                                        <div class="form-group">
                                            <textarea style="border-color:lightgrey;" name="deskripsi" cols="48" rows="5" required>{{ $penyakit->deskripsi }}</textarea>
                                            <p style="color:red;font-size:13px;">
                                                @if($errors->has('deskripsi'))
                                                <i class="fa fa-exclamation-circle"></i> {{$errors->first('deskripsi')}}
                                                @endif
                                            </p>
                                        </div>
                                    </div>
                                </div>
                                <div class="dt-buttons">
                                    <div class="sweetalert m-t-15">
                                        <button class="btn btn-info btn sweet-success" type="submit">Submit</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End PAge Content -->
    </div>
</div>
@endsection

resources/views/backend/daftar-penyakit/index.blade.php
@extends('backend.layouts.app')

@section('content')
<div class="page-wrapper">
    <!-- Bread crumb -->
    <div class="row page-titles">
        <div class="col-md-5 align-self-center">
            <h3 class="text-primary">Data Daftar  Penyakit</h3>
        </div>
        <div class="col-md-7 align-self-center">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
                <li class="breadcrumb-item active">Data Daftar  Penyakit</li>
            </ol>
        </div>
    </div>
    <!-- End Bread crumb -->
    <!-- Container fluid  -->
    <div class="container-fluid">
        <!-- Start Page Content -->
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <div class="table-responsive m-t-0">
                            <a href="{{ route('daftar-penyakit.create')}}" class="btn btn-info" name="button">Tambah Data Penyakit</a>
                            <table id="example23" class="display nowrap table table-hover table-striped table-bordered" cellspacing="0" width="100%">
                                <thead>
                                    <tr>
                                        <th>Nama</th>
                                        <th>Deskripsi</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($penyakit as $data)
                                        <tr>
                                            <td>{{ $data->nama_penyakit }}</td>
                                            <td>{{ $data->deskripsi }}</td>
                                            <td style="display:inline-flex;margin-left:15%;">
                                            <a href="{{ route('daftar-penyakit.edit', $data->id) }}" class="btn btn-warning" name="button"><i class="fa fa-pencil" aria-hidden="true"> </i></a>&nbsp;
                                            <!-- <button class="btn btn-danger btn sweet-confirm" form="{{ $data->id }}"><i class="fa fa-trash-o" aria-hidden="true"> </i></button> -->
                                            <form action="{{ route('daftar-penyakit.destroy',$data->id) }}" onsubmit="return confirm('Yakin ingin menghapus data ini?');" method="POST">
                                                <input type="hidden" name="_method" value="DELETE">
                                                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                                <button type="submit" class="btn btn-danger btn sweet-confirm"><i class="fa fa-trash-o" aria-hidden="true"> </i></button>
                                            </form>
                                        </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End PAge Content -->
    </div>
</div>
@endsection