routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// Auth::routes();

Route::get('/&&anakita-login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('/&&anakita-login', 'Auth\LoginController@login');
Route::post('/&&anakita-logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
Route::get('/&&anakita-register', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('/&&anakita-register', 'Auth\RegisterController@register');

Route::get('/&&anakita-password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('/&&anakita-password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('/&&anakita-password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('/&&anakita-password/reset', 'Auth\ResetPasswordController@reset')->name('password.update');




Route::get('/home', 'HomeController@index')->name('home');
Route::resource('/data-anak', 'DataAnakController');
Route::resource('/data-visual', 'DataVisualController');
Route::resource('/riwayat-vaksinasi', 'VaksinasiController');
Route::resource('/riwayat-kesehatan', 'KesehatanController');
Route::resource('/yayasan', 'YayasanController');
Route::resource('/user', 'UsersController');
Route::resource('/daftar-penyakit', 'DaftarPenyakitController');
// Route::resource('/log', 'AuditController');
    
Route::get('/profile/{id}','YayasanController@profile')->name('profile');
Route::post('/profile/{id}','YayasanController@updateProfile')->name('updateProfile');
Route::post('/data-anak/cari','DataAnakController@cari')->name('cariAnak');
Route::get('/log','HomeController@getAudit');


// Route for Excel and PDF Report
Route::get('excel/vaksinasi/{id}','VaksinasiController@export')->name('export.vaksinasi');
Route::get('excel/kesehatan/{id}','KesehatanController@export')->name('export.kesehatan');
Route::get('excel/data-anak/{id}','DataAnakController@export')->name('export.data-anak');
Route::get('excel/yayasan/{id}','YayasanController@export')->name('export.data-yayasan');

Route::get('pdf/vaksinasi/{id}', 'VaksinasiController@pdf')->name('pdf.vaksinasi');
Route::get('pdf/kesehatan/{id}', 'KesehatanController@pdf')->name('pdf.kesehatan');

Route::get('pdf/data-anak/{id}', 'DataAnakController@pdfDataAnak')->name('pdf.data-anak');
Route::get('pdf/data-anak/vaksinasi/{id}', 'DataAnakController@pdfVaksinasi')->name('pdf.data-anak.vaksinasi');
Route::get('pdf/data-anak/kesehatan/{id}', 'DataAnakController@pdfKesehatan')->name('pdf.data-anak.kesehatan');

Route::get('pdf/yayasan/{id}', 'YayasanController@pdfDataYayasan')->name('pdf.data-yayasan');
Route::get('pdf/yayasan/data-anak/{id}', 'YayasanController@pdfDataAnak')->name('pdf.data-yayasan.data-anak');
Route::get('pdf/yayasan/vaksinasi/{id}', 'YayasanController@pdfVaksinasi')->name('pdf.data-yayasan.vaksinasi');
Route::get('pdf/yayasan/kesehatan/{id}', 'YayasanController@pdfKesehatan')->name('pdf.data-yayasan.kesehatan');

app/User.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','role','id_yayasan',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function dataYayasan()
    {
        return $this->belongsTo('App\Models\Yayasan', 'id_yayasan', 'id');
    }
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use App\User;
use App\Models\Yayasan;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Crypt;

class UsersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['user'] = User::where('role','admin')->get();
        return view('backend.user.index',$data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['yayasan'] = Yayasan::all();
        return view('backend.user.create',$data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $check = User::where('email', '=', $request->email)->exists();
        if ($check) {
            return back()->withError($request->email.' sudah di gunakan');
        }

        $input['name'] = $request->name;
        $input['email'] = $request->email;
        $input['password'] = bcrypt($request->password);
        $input['id_yayasan'] = $request->id_yayasan;
        $input['role'] = "admin";
        User::create($input);

        return redirect()->route('user.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['user'] = User::find($id);
        $data['yayasan'] = User::all();
        return view('backend.user.edit',$data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = User::findOrFail($id);
        $check = User::where('email', '=', $request->email)->exists();
        if ($check) {
            return back()->withError($request->email . ' sudah di gunakan');
        }
        
        if ($request->password == "") {
            $data->password = $data->password;
        }else{
            $data->password = $request->password;
        }

        if ($request->id_yayasan == "") {
            $data->id_yayasan = $data->id_yayasan;
        }else{
            $data->id_yayasan = $request->id_yayasan;
        }

        $data->name = $request->name;
        $data->email = $request->email;
        $data->update();

        return redirect()->route('user.index');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $data = User::findOrFail($id);
        $data->delete();

        return redirect()->route('user.index');
    }
}

resources/views/backend/user/create.blade.php
@extends('backend.layouts.app')

@section('content')
<style>
    .form-control::-webkit-input-placeholder {
        font-size: 14px;
        color: darkgrey;
    }

    .form-control::-moz-input-placeholder {
        color: darkgrey;
    }

    .form-control:-ms-input-placeholder {
        color: darkgrey;
    }
</style>
<div class="page-wrapper">
    <!-- Bread crumb -->
    <div class="row page-titles">
        <div class="col-md-5 align-self-center">
            <h3 class="text-primary">User</h3>
        </div>
        <div class="col-md-7 align-self-center">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="javascript:void(0)">Tambah</a></li>
                <li class="breadcrumb-item active">User</li>
            </ol>
        </div>
    </div>
    <!-- End Bread crumb -->
    <!-- Container fluid  -->
    <div class="container-fluid">
        <!-- Start Page Content -->
        <!-- /# row -->
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-title">
                        <h4>Tambah User</h4>
                        @if (session('error'))
                        <div class="alert alert-danger">{{ session('error') }}</div>
                        @endif

                    </div>
                    <div class="card-body">
                        <div class="basic-elements">
                            <form action="{{ route('user.store') }}" enctype="multipart/form-data" method="post">
                                @csrf
                                <div class="row">
                                    <div class="col-lg-6">
                                        <div class="form-group">
                                            <label>Nama<span style="color:red;"> *</span></label>
                                            <input type="text" name="name" class="form-control" value="{{ old('name') }}" placeholder="Nama" required>
                                            <p style="color:red;font-size:13px;">
                                                @if($errors->has('name'))
                                                <i class="fa fa-exclamation-circle"></i> {{$errors->first('name')}}
                                                @endif
                                            </p>
                                        </div>
                                        <div class="form-group">
                                            <label>Email<span style="color:red;"> *</span></label>
                                            <input type="email" name="email" class="form-control" value="{{ old('email') }}" placeholder="Email" required>
                                            <p style="color:red;font-size:13px;">
                                                @if($errors->has('email'))
                                                <i class="fa fa-exclamation-circle"></i> {{$errors->first('email')}}
                                                @endif
                                            </p>
                                        </div>
                                        <div class="form-group">
                                            <label>Password<span style="color:red;"> *</span></label>
                                            <input type="password" name="password" class="form-control" value="{{ old('password') }}" placeholder="Password" required>
                                            <p style="color:red;font-size:13px;">
                                                @if($errors->has('password'))
                                                <i class="fa fa-exclamation-circle"></i> {{$errors->first('password')}}
                                                @endif
                                            </p>
                                        </div>
                                        <div class="form-group">
                                            <label>Yayasan<span style="color:red;"> *</span></label>
                                            <select class="form-control" name="id_yayasan" required>
                                                <option selected="true" disabled="disabled" value="{{ old('id_yayasan') }}">Pilih</option>
                                                @foreach($yayasan as $data)
                                                <option value="{{ $data->id }}">{{ $data->nama_yayasan }}</option>
                                                @endforeach
                                            </select>
                                            <p style="color:red;font-size:13px;">
                                                @if($errors->has('id_yayasan'))
                                                <i class="fa fa-exclamation-circle"></i> {{$errors->first('id_yayasan')}}
                                                @endif
                                            </p>
                                        </div>
                                    </div>
                                </div>
                                <div class="dt-buttons">
                                    <div class="sweetalert m-t-15">
                                        <button class="btn btn-info btn sweet-success" type="submit">Submit</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End PAge Content -->
    </div>
</div>
@endsection

resources/views/backend/user/edit.blade.php
@extends('backend.layouts.app')

@section('content')
<style>
    .form-control::-webkit-input-placeholder {
        font-size: 14px;
        color: darkgrey;
    }

    .form-control::-moz-input-placeholder {
        color: darkgrey;
    }

    .form-control:-ms-input-placeholder {
        color: darkgrey;
    }
</style>
<div class="page-wrapper">
    <!-- Bread crumb -->
    <div class="row page-titles">
        <div class="col-md-5 align-self-center">
            <h3 class="text-primary">User</h3>
        </div>
        <div class="col-md-7 align-self-center">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="javascript:void(0)">Tambah</a></li>
                <li class="breadcrumb-item active">User</li>
            </ol>
        </div>
    </div>
    <!-- End Bread crumb -->
    <!-- Container fluid  -->
    <div class="container-fluid">
        <!-- Start Page Content -->
        <!-- /# row -->
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-title">
                        <h4>Tambah User</h4>
                        @if (session('error'))
                        <div class="alert alert-danger">{{ session('error') }}</div>
                        @endif
                    </div>
                    <div class="card-body">
                        <div class="basic-elements">
                            <form action="{{ route('user.update',$user->id) }}" enctype="multipart/form-data" method="post">
                                @csrf
                                {{ method_field('PUT') }}
                                <div class="row">
                                    <div class="col-lg-6">
                                        <div class="form-group">
                                            <label>Nama<span style="color:red;"> *</span></label>
                                            <input type="text" name="name" class="form-control" value="{{ $user->name }}" placeholder="Nama" required>
                                            <p style="color:red;font-size:13px;">
                                                @if($errors->has('name'))
                                                <i class="fa fa-exclamation-circle"></i> {{$errors->first('name')}}
                                                @endif
                                            </p>
                                        </div>
                                        <div class="form-group">
                                            <label>Email<span style="color:red;"> *</span></label>
                                            <input type="email" name="email" class="form-control" value="{{ $user->email }}" placeholder="Email" required>
                                            <p style="color:red;font-size:13px;">
                                                @if($errors->has('email'))
                                                <i class="fa fa-exclamation-circle"></i> {{$errors->first('email')}}
                                                @endif
                                            </p>
                                        </div>
                                        <div class="form-group">
                                            <label>Password<span style="color:red;"> (jika tidak ingin mengubah password, maka kosongkan)</span></label>
                                            <input type="password" name="password" class="form-control" value="" placeholder="New Password">
                                            <p style="color:red;font-size:13px;">
                                                @if($errors->has('password'))
                                                <i class="fa fa-exclamation-circle"></i> {{$errors->first('password')}}
                                                @endif
                                            </p>
                                        </div>
                                        <div class="form-group">
                                            <label>Yayasan<span style="color:red;"> *</span></label>
                                            <select class="form-control" name="id_yayasan" value="{{ $user->id_yayasan }}">
                                                <option selected="true" disabled="disabled" value="{{ $user->id_yayasan }}">{{$user->dataYayasan->nama_yayasan}}</option>
                                                @foreach($yayasan as $data)
                                                <option value="{{ $data->id }}">{{ $data->nama_yayasan }}</option>
                                                @endforeach
                                            </select>
                                            <p style="color:red;font-size:13px;">
                                                @if($errors->has('id_yayasan'))
                                                <i class="fa fa-exclamation-circle"></i> {{$errors->first('id_yayasan')}}
                                                @endif
                                            </p>
                                        </div>
                                    </div>
                                </div>
                                <div class="dt-buttons">
                                    <div class="sweetalert m-t-15">
                                        <button class="btn btn-info btn sweet-success" type="submit">Submit</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End PAge Content -->
    </div>
</div>
@endsection

resources/views/backend/user/index.blade.php
@extends('backend.layouts.app')

@section('content')
<div class="page-wrapper">
    <!-- Bread crumb -->
    <div class="row page-titles">
        <div class="col-md-5 align-self-center">
            <h3 class="text-primary">Data User Admin</h3>
        </div>
        <div class="col-md-7 align-self-center">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
                <li class="breadcrumb-item active">Data User Admin</li>
            </ol>
        </div>
    </div>
    <!-- End Bread crumb -->
    <!-- Container fluid  -->
    <div class="container-fluid">
        <!-- Start Page Content -->
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <div class="table-responsive m-t-0">
                            <a href="{{ route('user.create')}}" class="btn btn-info" name="button">Tambah Data User</a>
                            <table id="example23" class="display nowrap table table-hover table-striped table-bordered" cellspacing="0" width="100%">
                                <thead>
                                    <tr>
                                        <th>Nama</th>
                                        <th>Email</th>
                                        <th>Role</th>
                                        <th>Nama Yayasan</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($user as $data)
                                    <tr>
                                        <td>{{ $data->name }}</td>
                                        <td>{{ $data->email }}</td>
                                        <td>{{ $data->role }}</td>
                                        <td>{{ $data->dataYayasan->nama_yayasan }}</td>
                                        <td style="display:inline-flex;margin-left:15%;">
                                            <a href="{{ route('user.edit', $data->id) }}" class="btn btn-warning" name="button"><i class="fa fa-pencil" aria-hidden="true"> </i></a>&nbsp;
                                            <!-- <button class="btn btn-danger btn sweet-confirm" form="{{ $data->id }}"><i class="fa fa-trash-o" aria-hidden="true"> </i></button> -->
                                            <form action="{{ route('user.destroy',$data->id) }}" onsubmit="return confirm('Yakin ingin menghapus data ini?');" method="POST">
                                                <input type="hidden" name="_method" value="DELETE">
                                                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                                <button type="submit" class="btn btn-danger btn sweet-confirm"><i class="fa fa-trash-o" aria-hidden="true"> </i></button>
                                            </form>
                                        </td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End PAge Content -->
    </div>
</div>
@endsection